### ISSUE TITLE
MPI+OpenMP with MPI_THREAD_MULTIPLE?

### ISSUE THREAD

**Issue by rzambre** [Exa-Graph/miniVite#2]
From quickly reading through the code, I see that only one thread is calling into the MPI library. This would be the `MPI_THREAD_FUNNELED` mode.

Is it possible (or would it even make sense) to partition the work on each node such that each thread is also involved in communication, that is, multiple threads call `MPI_Isend` and `MPI_Irecv` following the `MPI_THREAD_MULTIPLE` mode?

**Comment by Exa-Graph** [comment]
Yes, at present MPI calls are issued from a single thread. In the current vertex-based distribution, each process owns a portion of vertices (and all the edges connected to it, a.k.a ghost vertices, much like halos in stencil); every process then performs some local computation (using multiple threads), and exchanges updates. In the exchange update stage, in some places a process has to send/recv data to/from p processes (for e.g., see line 569 of dspl.hpp), and I guess thread_multiple could be used there in a straightforward fashion. So, I think we don't need to necessarily repartition to use thread_multiple. Does this make sense, I have little experience with thread_multiple, so feel free to criticize. - Sayan

**Comment by rzambre** [comment]
Yes, that makes sense. The idea would be to divide up sending/receiving to/from p processes between the threads in the process.

From my understanding of the code, each rank sends and receives from all other ranks (https://github.com/Exa-Graph/miniVite/blob/master/dspl.hpp#L602). However, rank i sends and receives non-zero-bytes only to and from rank i-1 and rank i+1; it sends and receives zero bytes from all the other ranks. Is this exchange of zero bytes with other ranks necessary?

**Comment by Exa-Graph** [comment]
"it sends and receives zero bytes from all the other ranks. Is this exchange of zero bytes with other ranks necessary?" >> that doesn't sound right. A rank can exchange with p-1 ranks, basically exchanging data with ghost vertex owners, which are spread over {0,p-1}. Lets continue this discussion over email if that's ok (zsayanz at gmail).
Update:
"However, rank i sends and receives non-zero-bytes only to and from rank i-1 and rank i+1; it sends and receives zero bytes from all the other ranks. Is this exchange of zero bytes with other ranks necessary?" >> This will happen for the default case when just "-n <#vertices>" is passed, in which a process only can communicate with its up/down neighbor (visualize a 1D vertex based distribution of the graph adjacency among p process). This is mentioned in the FAQs: https://github.com/Exa-Graph/miniVite/blob/master/FAQS#L183
However, we don't *prevent* 0 byte exchanges, as pointed out by @rzambre. This will be resolved in one of the future commits.
